/* GENERATED FILE — do not edit by hand.
 * Source: scripts/gen-codelists.py, 2026-09-24.
 * Mengdetype per IFC class: 155 classes from C:/workspace/skiplum/client-projects/10021-henrik-ibsens-gate-90/underprosjekter/HI90_Mottakskontroll/02_Arbeid/mengdetype_ifcklasse.yaml
 * (sha256 b7e450ee2eb38ddc85516a4807190774eda19928ae547868636d51e6213e57cd).
 */

import type { MengdetypeTable, OpenRulings } from "./types.ts";

export const MENGDETYPE_IFCKLASSE: MengdetypeTable = {
  meta: {"id": "mengdetype-ifcklasse", "label": "Mengdetype per IFC-klasse", "source": "C:/workspace/skiplum/client-projects/10021-henrik-ibsens-gate-90/underprosjekter/HI90_Mottakskontroll/02_Arbeid/mengdetype_ifcklasse.yaml", "sha256": "b7e450ee2eb38ddc85516a4807190774eda19928ae547868636d51e6213e57cd", "generated": "2026-09-24", "count": 155},
  rows: {
    "IfcActuator": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcAirTerminal": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcAirTerminalBox": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcAirToAirHeatRecovery": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcAlarm": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcAnnotation": {"mengdetype": "ikke_relevant", "ledeenhet": null},
    "IfcAudioVisualAppliance": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcBeam": {"mengdetype": "mengdeobjekt", "ledeenhet": "m3"},
    "IfcBeamStandardCase": {"mengdetype": "mengdeobjekt", "ledeenhet": "m3"},
    "IfcBoiler": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcBuilding": {"mengdetype": "ikke_relevant", "ledeenhet": null},
    "IfcBuildingElementPart": {"mengdetype": "ikke_relevant", "ledeenhet": null},
    "IfcBuildingElementProxy": {"mengdetype": "avhenger", "ledeenhet": null},
    "IfcBuildingStorey": {"mengdetype": "ikke_relevant", "ledeenhet": null},
    "IfcBurner": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcCableCarrierFitting": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcCableCarrierSegment": {"mengdetype": "mengdeobjekt", "ledeenhet": "m"},
    "IfcCableFitting": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcCableSegment": {"mengdetype": "mengdeobjekt", "ledeenhet": "m"},
    "IfcChiller": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcChimney": {"mengdetype": "mengdeobjekt", "ledeenhet": "m"},
    "IfcCivilElement": {"mengdetype": "avhenger", "ledeenhet": null},
    "IfcCoil": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcColumn": {"mengdetype": "mengdeobjekt", "ledeenhet": "m3"},
    "IfcColumnStandardCase": {"mengdetype": "mengdeobjekt", "ledeenhet": "m3"},
    "IfcCommunicationsAppliance": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcCompressor": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcCondenser": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcController": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcCooledBeam": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcCoolingTower": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcCovering": {"mengdetype": "mengdeobjekt", "ledeenhet": "m2"},
    "IfcCurtainWall": {"mengdetype": "mengdeobjekt", "ledeenhet": "m2"},
    "IfcDamper": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcDiscreteAccessory": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcDistributionChamberElement": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcDistributionControlElement": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcDistributionElement": {"mengdetype": "avhenger", "ledeenhet": null},
    "IfcDistributionFlowElement": {"mengdetype": "avhenger", "ledeenhet": null},
    "IfcDistributionPort": {"mengdetype": "ikke_relevant", "ledeenhet": null},
    "IfcDoor": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcDoorStandardCase": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcDuctFitting": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcDuctSegment": {"mengdetype": "mengdeobjekt", "ledeenhet": "m"},
    "IfcDuctSilencer": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcElectricAppliance": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcElectricDistributionBoard": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcElectricFlowStorageDevice": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcElectricGenerator": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcElectricMotor": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcElectricTimeControl": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcElementAssembly": {"mengdetype": "avhenger", "ledeenhet": null},
    "IfcEnergyConversionDevice": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcEngine": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcEvaporativeCooler": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcEvaporator": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcExternalSpatialElement": {"mengdetype": "ikke_relevant", "ledeenhet": null},
    "IfcFan": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcFastener": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcFilter": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcFireSuppressionTerminal": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcFlowController": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcFlowFitting": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcFlowInstrument": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcFlowMeter": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcFlowMovingDevice": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcFlowSegment": {"mengdetype": "mengdeobjekt", "ledeenhet": "m"},
    "IfcFlowStorageDevice": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcFlowTerminal": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcFlowTreatmentDevice": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcFooting": {"mengdetype": "mengdeobjekt", "ledeenhet": "m3"},
    "IfcFurnishingElement": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcFurniture": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcGeographicElement": {"mengdetype": "avhenger", "ledeenhet": null},
    "IfcGrid": {"mengdetype": "ikke_relevant", "ledeenhet": null},
    "IfcHeatExchanger": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcHumidifier": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcInterceptor": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcJunctionBox": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcLamp": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcLightFixture": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcMechanicalFastener": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcMedicalDevice": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcMember": {"mengdetype": "mengdeobjekt", "ledeenhet": "m3"},
    "IfcMemberStandardCase": {"mengdetype": "mengdeobjekt", "ledeenhet": "m3"},
    "IfcMotorConnection": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcOpeningElement": {"mengdetype": "ikke_relevant", "ledeenhet": null},
    "IfcOpeningStandardCase": {"mengdetype": "ikke_relevant", "ledeenhet": null},
    "IfcOutlet": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcPile": {"mengdetype": "mengdeobjekt", "ledeenhet": "m3"},
    "IfcPipeFitting": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcPipeSegment": {"mengdetype": "mengdeobjekt", "ledeenhet": "m"},
    "IfcPlate": {"mengdetype": "mengdeobjekt", "ledeenhet": "m2"},
    "IfcPlateStandardCase": {"mengdetype": "mengdeobjekt", "ledeenhet": "m2"},
    "IfcProjectionElement": {"mengdetype": "ikke_relevant", "ledeenhet": null},
    "IfcProtectiveDevice": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcProtectiveDeviceTrippingUnit": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcProxy": {"mengdetype": "avhenger", "ledeenhet": null},
    "IfcPump": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcRailing": {"mengdetype": "mengdeobjekt", "ledeenhet": "m"},
    "IfcRamp": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcRampFlight": {"mengdetype": "mengdeobjekt", "ledeenhet": "m2"},
    "IfcReinforcingBar": {"mengdetype": "mengdeobjekt", "ledeenhet": "m"},
    "IfcReinforcingMesh": {"mengdetype": "mengdeobjekt", "ledeenhet": "m"},
    "IfcRoof": {"mengdetype": "mengdeobjekt", "ledeenhet": "m2"},
    "IfcSanitaryTerminal": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcSensor": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcShadingDevice": {"mengdetype": "mengdeobjekt", "ledeenhet": "m2"},
    "IfcSite": {"mengdetype": "ikke_relevant", "ledeenhet": null},
    "IfcSlab": {"mengdetype": "mengdeobjekt", "ledeenhet": "m2"},
    "IfcSlabElementedCase": {"mengdetype": "mengdeobjekt", "ledeenhet": "m2"},
    "IfcSlabStandardCase": {"mengdetype": "mengdeobjekt", "ledeenhet": "m2"},
    "IfcSolarDevice": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcSpace": {"mengdetype": "ikke_relevant", "ledeenhet": null},
    "IfcSpaceHeater": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcSpatialZone": {"mengdetype": "ikke_relevant", "ledeenhet": null},
    "IfcStackTerminal": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcStair": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcStairFlight": {"mengdetype": "mengdeobjekt", "ledeenhet": "m2"},
    "IfcStructuralCurveAction": {"mengdetype": "ikke_relevant", "ledeenhet": null},
    "IfcStructuralCurveConnection": {"mengdetype": "ikke_relevant", "ledeenhet": null},
    "IfcStructuralCurveMember": {"mengdetype": "ikke_relevant", "ledeenhet": null},
    "IfcStructuralCurveMemberVarying": {"mengdetype": "ikke_relevant", "ledeenhet": null},
    "IfcStructuralCurveReaction": {"mengdetype": "ikke_relevant", "ledeenhet": null},
    "IfcStructuralLinearAction": {"mengdetype": "ikke_relevant", "ledeenhet": null},
    "IfcStructuralPlanarAction": {"mengdetype": "ikke_relevant", "ledeenhet": null},
    "IfcStructuralPointAction": {"mengdetype": "ikke_relevant", "ledeenhet": null},
    "IfcStructuralPointConnection": {"mengdetype": "ikke_relevant", "ledeenhet": null},
    "IfcStructuralPointReaction": {"mengdetype": "ikke_relevant", "ledeenhet": null},
    "IfcStructuralSurfaceAction": {"mengdetype": "ikke_relevant", "ledeenhet": null},
    "IfcStructuralSurfaceConnection": {"mengdetype": "ikke_relevant", "ledeenhet": null},
    "IfcStructuralSurfaceMember": {"mengdetype": "ikke_relevant", "ledeenhet": null},
    "IfcStructuralSurfaceMemberVarying": {"mengdetype": "ikke_relevant", "ledeenhet": null},
    "IfcStructuralSurfaceReaction": {"mengdetype": "ikke_relevant", "ledeenhet": null},
    "IfcSurfaceFeature": {"mengdetype": "ikke_relevant", "ledeenhet": null},
    "IfcSwitchingDevice": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcSystemFurnitureElement": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcTank": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcTendon": {"mengdetype": "mengdeobjekt", "ledeenhet": "m"},
    "IfcTendonAnchor": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcTransformer": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcTransportElement": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcTubeBundle": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcUnitaryControlElement": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcUnitaryEquipment": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcValve": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcVibrationIsolator": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcVirtualElement": {"mengdetype": "ikke_relevant", "ledeenhet": null},
    "IfcVoidingFeature": {"mengdetype": "ikke_relevant", "ledeenhet": null},
    "IfcWall": {"mengdetype": "mengdeobjekt", "ledeenhet": "m2"},
    "IfcWallElementedCase": {"mengdetype": "mengdeobjekt", "ledeenhet": "m2"},
    "IfcWallStandardCase": {"mengdetype": "mengdeobjekt", "ledeenhet": "m2"},
    "IfcWasteTerminal": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcWindow": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
    "IfcWindowStandardCase": {"mengdetype": "telleobjekt", "ledeenhet": "stk"},
  },
};

/** The open rulings on the tables, not decided here: the report says «åpen»
 *  where they touch the switch. From C:/workspace/skiplum/client-projects/10021-henrik-ibsens-gate-90/underprosjekter/HI90_Mottakskontroll/02_Arbeid/krav.yaml
 *  (sha256 0005600fa95831493ae14a3809b8eb1499dfd429ce6ad090692457c8af7e96a8), materialprodukt.aapne. */
export const MENGDETYPE_AAPNE: OpenRulings = {
  meta: {"id": "mengdetype-aapne", "label": "Åpne kjennelser, mengdetype", "source": "C:/workspace/skiplum/client-projects/10021-henrik-ibsens-gate-90/underprosjekter/HI90_Mottakskontroll/02_Arbeid/krav.yaml", "sha256": "0005600fa95831493ae14a3809b8eb1499dfd429ce6ad090692457c8af7e96a8", "generated": "2026-09-24", "count": 4},
  rulings: [{"tittel": "Dør og vindu", "klasser": ["IfcDoor", "IfcDoorStandardCase", "IfcWindow", "IfcWindowStandardCase"]}, {"tittel": "Dekke og tak", "klasser": ["IfcSlab", "IfcSlabStandardCase", "IfcSlabElementedCase", "IfcRoof"]}, {"tittel": "Trappeløp og rampeløp", "klasser": ["IfcStairFlight", "IfcRampFlight"]}, {"tittel": "Prefab-moduler", "klasser": []}],
};
