/** A bundled code list: a plain lookup from code to Norwegian name.
 *
 * Generated by scripts/gen-codelists.py. `meta` is the provenance: which source
 * table, its hash, when it was generated and how many codes it holds. */

export interface CodeListMeta {
  id: string;
  /** Short display label, e.g. "NS 3457-8". */
  label: string;
  edition: string;
  /** Absolute path of the source table on the machine that generated it. */
  source: string;
  sha256: string;
  /** A second table the source was compared against, code by code. */
  crossChecked?: string;
  /** ISO date. */
  generated: string;
  count: number;
}

export interface CodeList {
  meta: CodeListMeta;
  codes: Readonly<Record<string, string>>;
}

/** Telleobjekt or mengdeobjekt, per IFC class or per component code
 *  (Ed-Skiplum/ifc-check#1, gap 3). Generated by scripts/gen-codelists.py from
 *  the HI90 mottakskontroll's two hand-set tables; each row is a
 *  recommendation, never a computed value. Not a CodeList: nothing looks a code
 *  up in it for validity, and it is not in CODE_LISTS. */
export type Mengdetype = "telleobjekt" | "mengdeobjekt" | "avhenger" | "ikke_relevant";

export interface MengdetypeMeta {
  id: string;
  label: string;
  source: string;
  sha256: string;
  generated: string;
  count: number;
}

export interface MengdetypeTable {
  meta: MengdetypeMeta;
  rows: Readonly<Record<string, { mengdetype: Mengdetype; ledeenhet: string | null }>>;
}

/** Rulings on the tables that are open: the tables still answer for those
 *  classes, and the report marks the answer «åpen». A ruling with no classes
 *  cannot be told apart per object. */
export interface OpenRulings {
  meta: MengdetypeMeta;
  rulings: readonly { tittel: string; klasser: readonly string[] }[];
}
