/** A bundled code list: a plain lookup from code to Norwegian name.
 *
 * Generated by scripts/gen-codelists.py. `meta` is the provenance: which source
 * table, its hash, when it was generated and how many codes it holds. */

/** A name the generator changed against the earlier table it cross-checks,
 *  verified on the source page. `was` null = the code was missing there. */
export interface CodeListCorrection {
  code: string;
  was: string | null;
  now: string;
  /** Page of the source PDF the name was verified on. */
  page: number;
}

export interface CodeListMeta {
  id: string;
  /** Short display label, e.g. "NS 3457-8". */
  label: string;
  edition: string;
  /** Absolute path of the source table on the machine that generated it. */
  source: string;
  sha256: string;
  /** A second table the source was compared against, code by code. */
  crossChecked?: string;
  /** Where the source and `crossChecked` disagree, with the page each name
   *  was verified on. */
  corrections?: CodeListCorrection[];
  /** Codes whose name was read off the rendered page image because the
   *  source's text layer is damaged there. */
  readFromImage?: string[];
  /** Codes whose name could not be verified against the source. */
  unverified?: string[];
  /** ISO date. */
  generated: string;
  count: number;
  /** Size of `reserved`, when the list has reserved codes. */
  reservedCount?: number;
}

export interface CodeList {
  meta: CodeListMeta;
  codes: Readonly<Record<string, string>>;
  /** Codes the standard reserves ("Koden skal ikke benyttes"). They are in
   *  `codes` too, so a lookup tells a reserved code from an unknown one.
   *  Whether a reserved code is acceptable is a project ruling, not the
   *  list's. */
  reserved?: readonly string[];
}

/** Telleobjekt or mengdeobjekt, per IFC class or per component code
 *  (Ed-Skiplum/ifc-check#1, gap 3). Generated by scripts/gen-codelists.py from
 *  the HI90 mottakskontroll's two hand-set tables; each row is a
 *  recommendation, never a computed value. Not a CodeList: nothing looks a code
 *  up in it for validity, and it is not in CODE_LISTS. */
export type Mengdetype = "telleobjekt" | "mengdeobjekt" | "avhenger" | "ikke_relevant";

export interface MengdetypeMeta {
  id: string;
  label: string;
  source: string;
  sha256: string;
  generated: string;
  count: number;
}

export interface MengdetypeTable {
  meta: MengdetypeMeta;
  rows: Readonly<Record<string, { mengdetype: Mengdetype; ledeenhet: string | null }>>;
}

/** Rulings on the tables that are open: the tables still answer for those
 *  classes, and the report marks the answer «åpen». A ruling with no classes
 *  cannot be told apart per object. */
export interface OpenRulings {
  meta: MengdetypeMeta;
  rulings: readonly { tittel: string; klasser: readonly string[] }[];
}
